language: node_js

node_js: 'node'

script:
  - npm run lint
  - npm test

before_deploy: npm i now --no-save

deploy:
  - provider: script
    script: now --token $NOW_TOKEN --target production
    skip_cleanup: true
    on:
      branch: master
      condition: $TRAVIS_EVENT_TYPE = push

  - provider: script
    script: now --token $NOW_TOKEN --target staging && now alias autapomorph-forecast-git-$TRAVIS_BRANCH --token $NOW_TOKEN
    skip_cleanup: true
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH != master && $TRAVIS_EVENT_TYPE = push
