version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:13.7
    steps:
      - checkout

      # Install and cache dependencies
      - restore_cache:
          keys:
            - npm-deps-{{ checksum "package-lock.json" }}
            - npm-deps-
      - run: npm install
      - save_cache:
          key: npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      # linting
      - run:
          name: Lint
          command: npm run lint

      # testing
      - run:
      - run:
          name: Install jest-junit
          command: npm i -D jest-junit
      - run:
          name: Test
          environment:
            JEST_JUNIT_OUTPUT_DIR: coverage/test-results/jest
          command: npm test -- --ci --coverage --reporters=default --reporters=jest-junit
      - store_artifacts:
          path: coverage
          destination: coverage
      - store_test_results:
          path: coverage/test-results
