version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:13.7

commands:
  install-deps:
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            - v1-npm-deps-
      - run: npm install
      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
jobs:
  lint:
    executor: node
    steps:
      - install-deps
      - run:
          name: Lint
          command: npm run lint

  test:
    executor: node
    steps:
      - install-deps
      - run:
          name: Test
          command: npm test -- --maxWorkers=2 --coverage --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: coverage/test-results/jest
      - store_artifacts:
          path: coverage
          destination: coverage
      - store_test_results:
          path: coverage/test-results

workflows:
  version: 2
  build:
    jobs:
      - lint
      - test
